/*
 *      ** File generated automatically, do not modify **
 *
*/

#ifndef __visp_core_h_
#define __visp_core_h_

#include <visp3/core/vpConfig.h>
#include <visp3/core/vpArray2D.h>
#include <visp3/core/vpBSpline.h>
#include <visp3/core/vpCPUFeatures.h>
#include <visp3/core/vpCameraParameters.h>
#include <visp3/core/vpCircle.h>
#include <visp3/core/vpClient.h>
#include <visp3/core/vpColVector.h>
#include <visp3/core/vpColor.h>
#include <visp3/core/vpConvert.h>
#include <visp3/core/vpCylinder.h>
#include <visp3/core/vpDebug.h>
#include <visp3/core/vpDisplay.h>
#include <visp3/core/vpDisplayException.h>
#include <visp3/core/vpEigenConversion.h>
#include <visp3/core/vpException.h>
#include <visp3/core/vpExponentialMap.h>
#include <visp3/core/vpFeatureDisplay.h>
#include <visp3/core/vpForceTwistMatrix.h>
#include <visp3/core/vpForwardProjection.h>
#include <visp3/core/vpFrameGrabber.h>
#include <visp3/core/vpFrameGrabberException.h>
#include <visp3/core/vpGEMM.h>
#include <visp3/core/vpGaussRand.h>
#include <visp3/core/vpHinkley.h>
#include <visp3/core/vpHistogram.h>
#include <visp3/core/vpHistogramPeak.h>
#include <visp3/core/vpHistogramValey.h>
#include <visp3/core/vpHomogeneousMatrix.h>
#include <visp3/core/vpImage.h>
#include <visp3/core/vpImageConvert.h>
#include <visp3/core/vpImageException.h>
#include <visp3/core/vpImageFilter.h>
#include <visp3/core/vpImageMorphology.h>
#include <visp3/core/vpImagePoint.h>
#include <visp3/core/vpImageTools.h>
#include <visp3/core/vpIoException.h>
#include <visp3/core/vpIoTools.h>
#include <visp3/core/vpKalmanFilter.h>
#include <visp3/core/vpLinProg.h>
#include <visp3/core/vpLine.h>
#include <visp3/core/vpLinearKalmanFilterInstantiation.h>
#include <visp3/core/vpList.h>
#include <visp3/core/vpMath.h>
#include <visp3/core/vpMatrix.h>
#include <visp3/core/vpMatrixException.h>
#include <visp3/core/vpMeterPixelConversion.h>
#include <visp3/core/vpMoment.h>
#include <visp3/core/vpMomentAlpha.h>
#include <visp3/core/vpMomentArea.h>
#include <visp3/core/vpMomentAreaNormalized.h>
#include <visp3/core/vpMomentBasic.h>
#include <visp3/core/vpMomentCInvariant.h>
#include <visp3/core/vpMomentCentered.h>
#include <visp3/core/vpMomentCommon.h>
#include <visp3/core/vpMomentDatabase.h>
#include <visp3/core/vpMomentGravityCenter.h>
#include <visp3/core/vpMomentGravityCenterNormalized.h>
#include <visp3/core/vpMomentObject.h>
#include <visp3/core/vpMouseButton.h>
#include <visp3/core/vpMutex.h>
#include <visp3/core/vpNetwork.h>
#include <visp3/core/vpNoise.h>
#include <visp3/core/vpPixelMeterConversion.h>
#include <visp3/core/vpPlane.h>
#include <visp3/core/vpPoint.h>
#include <visp3/core/vpPolygon.h>
#include <visp3/core/vpPolygon3D.h>
#include <visp3/core/vpPoseVector.h>
#include <visp3/core/vpQuadProg.h>
#include <visp3/core/vpQuaternionVector.h>
#include <visp3/core/vpRGBa.h>
#include <visp3/core/vpRansac.h>
#include <visp3/core/vpRect.h>
#include <visp3/core/vpRectOriented.h>
#include <visp3/core/vpRequest.h>
#include <visp3/core/vpRobust.h>
#include <visp3/core/vpRotationMatrix.h>
#include <visp3/core/vpRotationVector.h>
#include <visp3/core/vpRowVector.h>
#include <visp3/core/vpRxyzVector.h>
#include <visp3/core/vpRzyxVector.h>
#include <visp3/core/vpRzyzVector.h>
#include <visp3/core/vpScale.h>
#include <visp3/core/vpSerial.h>
#include <visp3/core/vpServer.h>
#include <visp3/core/vpSphere.h>
#include <visp3/core/vpSubColVector.h>
#include <visp3/core/vpSubMatrix.h>
#include <visp3/core/vpSubRowVector.h>
#include <visp3/core/vpThetaUVector.h>
#include <visp3/core/vpThread.h>
#include <visp3/core/vpTime.h>
#include <visp3/core/vpTracker.h>
#include <visp3/core/vpTrackingException.h>
#include <visp3/core/vpTranslationVector.h>
#include <visp3/core/vpTriangle.h>
#include <visp3/core/vpUDPClient.h>
#include <visp3/core/vpUDPServer.h>
#include <visp3/core/vpUniRand.h>
#include <visp3/core/vpVelocityTwistMatrix.h>
#include <visp3/core/vpXmlParser.h>
#include <visp3/core/vpXmlParserCamera.h>
#include <visp3/core/vpXmlParserHomogeneousMatrix.h>
#include <visp3/core/vpXmlParserRectOriented.h>
#include <visp3/core/vpConfig.h>
#include <visp3/visp_modules.h>

#endif

